### ISSUE TITLE
Fallo en el título

### ISSUE THREAD

**Issue by Sergiosan12** [Sergiosan12/IssuesKS#5]
https://github.com/Sergiosan12/IssuesKS/blob/b4569f12dd3760dd0b1a5698cec61acdd784b441/src/Main.java#L4

**Comment by kiglesiasesteves** [comment]
Sergio,cual es la modificación?

**Comment by Sergiosan12** [comment]
La que está despedida es Keyla

**Comment by kiglesiasesteves** [comment]
Ah vale, voy a corregirlo
